export const availableColors = {
  light: [
    { color: '#F2F2F2', name: 'White' },
    { color: '#E0E0E0', name: 'Light gray' },
    { color: '#B0BEC5', name: 'Light blue-gray' },
    { color: '#9E9E9E', name: 'Gray' },
    { color: '#A5D6A7', name: 'Light green' },
    { color: '#81C784', name: 'Soft green' },
    { color: '#66BB6A', name: 'Medium green' },
    { color: '#4CAF50', name: 'Green' },
    { color: '#B3E5FC', name: 'Light blue' },
    { color: '#81D4FA', name: 'Soft blue' },
    { color: '#4FC3F7', name: 'Medium blue' },
    { color: '#29B6F6', name: 'Bright blue' },
    { color: '#FFF9C4', name: 'Light yellow' },
    { color: '#FFF59D', name: 'Soft yellow' },
    { color: '#FFEB3B', name: 'Bright yellow' },
    { color: '#FFC107', name: 'Amber' },
    { color: '#FFE0B2', name: 'Light orange' },
    { color: '#FFCC80', name: 'Soft orange' },
    { color: '#FFB74D', name: 'Medium orange' },
    { color: '#FF9800', name: 'Bright orange' },
    { color: '#FFCDD2', name: 'Light pink' },
    { color: '#EF9A9A', name: 'Soft pink' },
    { color: '#E57373', name: 'Medium pink' },
    { color: '#F44336', name: 'Red' },
    { color: '#E1BEE7', name: 'Light purple' },
    { color: '#D1C4E9', name: 'Soft lavender' },
    { color: '#9575CD', name: 'Medium purple' },
    { color: '#673AB7', name: 'Purple' },
  ],
  dark: [
    { color: '#757575', name: 'Dark gray' },
    { color: '#616161', name: 'Medium gray' },
    { color: '#424242', name: 'Darker gray' },
    { color: '#212121', name: 'Black' },
    { color: '#43A047', name: 'Dark green' },
    { color: '#388E3C', name: 'Deeper green' },
    { color: '#2E7D32', name: 'Darker green' },
    { color: '#1B5E20', name: 'Forest green' },
    { color: '#1976D2', name: 'Dark blue' },
    { color: '#1565C0', name: 'Deeper blue' },
    { color: '#0f5db7', name: 'Blue' },
    { color: '#0D47A1', name: 'Navy blue' },
    { color: '#FFB300', name: 'Dark amber' },
    { color: '#FFA000', name: 'Deep amber' },
    { color: '#FF8F00', name: 'Dark golden yellow' },
    { color: '#FF6F00', name: 'Dark orange-yellow' },
    { color: '#FB8C00', name: 'Dark orange' },
    { color: '#F57C00', name: 'Deeper orange' },
    { color: '#EF6C00', name: 'Darker orange' },
    { color: '#E65100', name: 'Very dark orange' },
    { color: '#E53935', name: 'Dark red' },
    { color: '#D32F2F', name: 'Deeper red' },
    { color: '#C62828', name: 'Darker red' },
    { color: '#B71C1C', name: 'Very dark red' },
    { color: '#5E35B1', name: 'Dark purple' },
    { color: '#512DA8', name: 'Deeper purple' },
    { color: '#4527A0', name: 'Darker purple' },
    { color: '#311B92', name: 'Very dark purple' },
  ],
}

export const mostUsedColors = {
  light: ['White', 'Soft green', 'Soft blue', 'Soft yellow', 'Soft orange', 'Soft pink', 'Soft lavender'],
  dark: ['Black', 'Dark green', 'Dark blue', 'Dark amber', 'Dark orange', 'Dark red', 'Dark purple'],
}
